### ISSUE TITLE
info pages reallllllllly slow to load

### ISSUE THREAD

**Issue by alexbaden** [neurodata/ndstore#222]
All of the info pages are pretty slow. I am not sure when it started, but I feel like I was able to load them this morning. Is it possible this is a cortex/LIMS issue?

http://openconnecto.me/ocp/ca/kasthuri11/info/ 

@randalburns @jovo @kunallillaney @j6k4m8

**Comment by kunallillaney** [comment]
Seems to be working fine for me. Also, LIMS issue is resolved with the new push.

**Comment by jovo** [comment]
working fine now for me.
an hour ago, the link above wasn't working at all.

On Mon, Feb 22, 2016 at 9:26 PM, Kunal Lillaney <notifications@github.com>
wrote:

> Seems to be working fine for me. Also, LIMS issue is resolved with the new
> push.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndstore/issues/222#issuecomment-187488973>.
>



-- 
the glass is all full:  half water, half air.
neurodata.io

**Comment by kunallillaney** [comment]
@jovo Well it was not working because it was broken.

**Comment by jovo** [comment]
well, i'm glad its fixed now :)

On Mon, Feb 22, 2016 at 9:33 PM, Kunal Lillaney <notifications@github.com>
wrote:

> @jovo <https://github.com/jovo> Well it was not working because it was
> broken.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurodata/ndstore/issues/222#issuecomment-187490342>.
>



-- 
the glass is all full:  half water, half air.
neurodata.io

**Comment by alexbaden** [comment]
Looks good now. I guess there isn't much we can do about loading metadata -- if cortex / LIMS goes down, it could take the info page down, too. Might make sense to separate the LIMS data from the data on info, so that if LIMS goes down you can still get the basics from ndstore.

**Comment by kunallillaney** [comment]
No it will not take it down. It returns irrespective of the metadata call failing.

**Comment by alexbaden** [comment]
If you get an error, sure. But if the server is down, you won't get an
error -- you just timeout. So, is the timeout of the metadata call lower
than the general nginx timeout? If not, nginx won't know if uwsgi timed
out, or the metadata call timed out, and will throw a 504 gateway timeout
error.

**Comment by alexbaden** [comment]
I think figured out what the issue I was having was -- if `settings.LIMS_SERVER` isn't defined, the page doesn't load when running through uwsgi. It looks like the exception `AttributeError` isn't caught, so the function `metadatadict` returns nothing. I couldn't replicate it on the dev server, but even adding `LIMS_SERVER = ''` to brainviz fixed the issue. 

Seems like this could be fixed by adding a catch for `AttributeError` if `LIMS_SERVER` isn't defined in `settings.py`.

That would also help with my ndv load times. On servers that don't use LIMS, load times for all ndv pages are increased by 5 seconds because I have to query projinfo to get dataset parameters. I don't think it's reasonable to expect all servers to use LIMS. The `try - except` method above fixes this problem. 

@randalburns @kunallillaney what do you think? I tested it and it seems to work.

**Comment by j6k4m8** [comment]
might be worth having a super fast timeout — if our servers (both local to JH) can't get a ping in ≈1sec, that might be adequate to just abort the LIMS call and return projinfo alone. Seems kinda janky though...

(Note: up until recently when @kunallillaney added this functionality, I was calling projinfo from ndio, and populating the `metadata` key after-the-fact.)

I definitely agree that this should be an optional feature. Not 100% convinced that lims belongs in projinfo at all, but I think we like having everything in the same place generally, and given that data requests can take O(days), metadata requests might not be the right place to (seconds-level) optimize. Thoughts?
